// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/document_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_document_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_document_service_proto_rawDescGZIP(), []int{0}
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType      string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	ChunkData     []byte                 `protobuf:"bytes,5,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentRequest) Reset() {
	*x = UploadDocumentRequest{}
	mi := &file_proto_document_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentRequest) ProtoMessage() {}

func (x *UploadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentRequest.ProtoReflect.Descriptor instead.
func (*UploadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_document_service_proto_rawDescGZIP(), []int{1}
}

func (x *UploadDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UploadDocumentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadDocumentRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadDocumentRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *UploadDocumentRequest) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

type UploadDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DocumentHash  string                 `protobuf:"bytes,3,opt,name=document_hash,json=documentHash,proto3" json:"document_hash,omitempty"`
	OffChainUrl   string                 `protobuf:"bytes,4,opt,name=off_chain_url,json=offChainUrl,proto3" json:"off_chain_url,omitempty"`
	TransactionId string                 `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentResponse) Reset() {
	*x = UploadDocumentResponse{}
	mi := &file_proto_document_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentResponse) ProtoMessage() {}

func (x *UploadDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentResponse.ProtoReflect.Descriptor instead.
func (*UploadDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_document_service_proto_rawDescGZIP(), []int{2}
}

func (x *UploadDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadDocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadDocumentResponse) GetDocumentHash() string {
	if x != nil {
		return x.DocumentHash
	}
	return ""
}

func (x *UploadDocumentResponse) GetOffChainUrl() string {
	if x != nil {
		return x.OffChainUrl
	}
	return ""
}

func (x *UploadDocumentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UploadDocumentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetDocumentInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentInfoRequest) Reset() {
	*x = GetDocumentInfoRequest{}
	mi := &file_proto_document_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentInfoRequest) ProtoMessage() {}

func (x *GetDocumentInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_document_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetDocumentInfoRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type GetDocumentInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	DocumentHash  string                 `protobuf:"bytes,3,opt,name=document_hash,json=documentHash,proto3" json:"document_hash,omitempty"`
	OffChainUrl   string                 `protobuf:"bytes,4,opt,name=off_chain_url,json=offChainUrl,proto3" json:"off_chain_url,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,6,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType      string                 `protobuf:"bytes,7,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentInfoResponse) Reset() {
	*x = GetDocumentInfoResponse{}
	mi := &file_proto_document_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentInfoResponse) ProtoMessage() {}

func (x *GetDocumentInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_document_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetDocumentInfoResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetDocumentInfoResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GetDocumentInfoResponse) GetDocumentHash() string {
	if x != nil {
		return x.DocumentHash
	}
	return ""
}

func (x *GetDocumentInfoResponse) GetOffChainUrl() string {
	if x != nil {
		return x.OffChainUrl
	}
	return ""
}

func (x *GetDocumentInfoResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDocumentInfoResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetDocumentInfoResponse) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

var File_proto_document_service_proto protoreflect.FileDescriptor

const file_proto_document_service_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/document_service.proto\x12\x10document_service\"%\n" +
	"\tFileChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"\xaa\x01\n" +
	"\x15UploadDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x05 \x01(\fR\tchunkData\"\xd2\x01\n" +
	"\x16UploadDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rdocument_hash\x18\x03 \x01(\tR\fdocumentHash\x12\"\n" +
	"\roff_chain_url\x18\x04 \x01(\tR\voffChainUrl\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"9\n" +
	"\x16GetDocumentInfoRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"\xec\x01\n" +
	"\x17GetDocumentInfoResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12#\n" +
	"\rdocument_hash\x18\x03 \x01(\tR\fdocumentHash\x12\"\n" +
	"\roff_chain_url\x18\x04 \x01(\tR\voffChainUrl\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x06 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\a \x01(\tR\bfileType2\xe0\x01\n" +
	"\x0fDocumentService\x12e\n" +
	"\x0eUploadDocument\x12'.document_service.UploadDocumentRequest\x1a(.document_service.UploadDocumentResponse(\x01\x12f\n" +
	"\x0fGetDocumentInfo\x12(.document_service.GetDocumentInfoRequest\x1a).document_service.GetDocumentInfoResponseB.Z,github.com/wailbentafat/fabrid_service/protob\x06proto3"

var (
	file_proto_document_service_proto_rawDescOnce sync.Once
	file_proto_document_service_proto_rawDescData []byte
)

func file_proto_document_service_proto_rawDescGZIP() []byte {
	file_proto_document_service_proto_rawDescOnce.Do(func() {
		file_proto_document_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_document_service_proto_rawDesc), len(file_proto_document_service_proto_rawDesc)))
	})
	return file_proto_document_service_proto_rawDescData
}

var file_proto_document_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_document_service_proto_goTypes = []any{
	(*FileChunk)(nil),               // 0: document_service.FileChunk
	(*UploadDocumentRequest)(nil),   // 1: document_service.UploadDocumentRequest
	(*UploadDocumentResponse)(nil),  // 2: document_service.UploadDocumentResponse
	(*GetDocumentInfoRequest)(nil),  // 3: document_service.GetDocumentInfoRequest
	(*GetDocumentInfoResponse)(nil), // 4: document_service.GetDocumentInfoResponse
}
var file_proto_document_service_proto_depIdxs = []int32{
	1, // 0: document_service.DocumentService.UploadDocument:input_type -> document_service.UploadDocumentRequest
	3, // 1: document_service.DocumentService.GetDocumentInfo:input_type -> document_service.GetDocumentInfoRequest
	2, // 2: document_service.DocumentService.UploadDocument:output_type -> document_service.UploadDocumentResponse
	4, // 3: document_service.DocumentService.GetDocumentInfo:output_type -> document_service.GetDocumentInfoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_document_service_proto_init() }
func file_proto_document_service_proto_init() {
	if File_proto_document_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_document_service_proto_rawDesc), len(file_proto_document_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_document_service_proto_goTypes,
		DependencyIndexes: file_proto_document_service_proto_depIdxs,
		MessageInfos:      file_proto_document_service_proto_msgTypes,
	}.Build()
	File_proto_document_service_proto = out.File
	file_proto_document_service_proto_goTypes = nil
	file_proto_document_service_proto_depIdxs = nil
}
